### ISSUE TITLE
minor: calling TiledGroupLayer#read_array with zero height gives an odd assertion error

### ISSUE THREAD

**Issue by robinmessage** [carboncredits/yirgacheffe#3]
Because no data is actually loaded (because none has been requested), there is an assertion error at the end of the function (https://github.com/carboncredits/yirgacheffe/blob/272e420b1579d40fad1a6090956f2e569b5353a3/yirgacheffe/layers/group.py#L281)

Should probably just assert width and height > 0

**Comment by mdales** [comment]
Fixed in 0f60a58
